language: java
sudo: false
notifications:
  slack:
    secure: f2lylRvGcAr6C+boZ/weJ6Hvb2FcK8oE2SL9AuXaoh9pTHM6vg22IUMswroE4dj5njYoS0+N64yjWd2r+D5sE+qmcGc/3Yb6XcGxP204x06nERDhv/kVbgrwgUlLxinWJLtoAvXwHOy1zolyGa7WgmYZ4znN1tAoD1OUL51PTsv/7IUzm0SXqsP3+BlFt83snEyI/WCONgS/gxVwnh0ciUVg228pj93LREdk/iO1Zn8XqhxGGXtqVnPUJ0UidB6IzMVkpaiVPO7hCNnwIhmS7ZDNXtUFSD0JzKYrpSVhga/cXJ4NN6MtJ9g5fwERVHtQXfKV+O2nqvVO9uGOIq1s1kF4LeVT555Z+Diwpn7G4B8WqhFeW3veGU/KqzXT09rQnxmLONKlEK2zr8Bx4C8ZOx9TLW5ELO+vXJliPM7I/umaAaQWaFoCNGnsdFY/aXcp3/ASe8ob5VtO8EV29hh1daab0k9NxdHk6XwqZOT7ex4agEs0A9smGyvrjkNQ5eOJDy6U35dBHi9ilNv62c8QDlG6hgCZwIBfsucwvY31HcJvmElhzBdei2KKIaljl5UQy3RRT1C99dI+88PKOoURMI+whmQxa+0Cuek46J4opGFeSLlreP7GVtYLFxnlaA97RZYswIthlaxBMiV8zdG2k6Q22hkb2GIX1GpE5m5TyU4=
deploy:
  provider: releases
  api_key:
    secure: rPws75EywWXAAwdicvt8U8nPXPOE8JQ2EDTuBWvXOqjsNdRCuEnTsjjKYLANlVrV2BxAIBYARhDbCl0F0LeEsd6lyEcbAqsfW6hdCTgvxUmT4UVJCvvI+lDFNa8J4Q3EKp1ecITUWtEYIBpnDyR0H+CDaNCqJDa4Q1CpV23l+HEpOwS7162ljv8KYAnV0ZWJ792gODotJqRbmuZohxu/svUJAjv5Yrwcpc/QVWEZePD40LtZjz12K4gzLjtIrhIMXwRITKNfJc6orlk+T+mjDUJEmQr8eJnlhmiDOKOD8JpywYJ0FiwIRsna1TVSFmEyL8hlrV/DwBsMBL1ZOS30w3KOWbGzvyCtVotluCujAqwwLZ/xP8BpkGK0UOHEiiBY7HSDE/z++9b2rIZ8m7kcmrnJVVnNxTwyDrFeVe7XbSDiBO4SQjSGnsGz4YHd/eIrgKoneM1foGruUCskK8/BdQtsRBq00FOBfZnA9iDesRVui/jwRjrg23trLNA8zNnRVBq7XZ81oGwy/WwzhYKeyScSSpm8cm6do5PZi+twDeqXMGVF3V5j9tsMLWx9MVEyVT8nPwfeAkTl2Je16lMxl0E1YaYQf1B5SkKpEFx+exePBL0lJjKP2jicT8VkyuYE6b20U83uSkXgQHDUCUFvcKAO6+VRZvFfTLQ6EtQs2VE=
  file: build/libs/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: xebialabs-community/xld-logreport-plugin
