language: java
jdk: openjdk8
deploy:
  provider: releases
  api_key:
    secure: RsTPWkYZ3B4frUe7p50KdIkP2MRqziXa6nfYv1m5R1BC/ww/lqKaURBRAIcRzQePZblfnAC5ShBLYljuwrRT9d9vfus0jkhzdvaekkqIZJfvQ0KSi+AGiqg9GJx3GlmaOS2sGrLVYdDr3YH8aMHPL/Enve4e6B1EnSv9clB/+UVJHhB25j0dp7FVtly4WNQI+TkvL2mYD6T96BofRLvkmpi4+KZiZZTPRLd1H8e7lJoqV/XPAyRtTHQp3omF/W8ruf2vldp0ur++mOFyWDN30epnXpGAXqmZx8oX5kYVLUkkGFl+wQl4v4yvjcjvqpv58lTjPW3PCzZxV65HSR2bJDy/RvfkTbvW3gkw01ulrkiI5H9EO7m6JmgufLH3E9pnV72TpkZ6pbyFYkGDyrhok2YZSXVpOnybpQdpUrapsr4mHOysszNv/qzCW4RHjHHawf6Hyx4QC9UdNr+2/t/adzBa55OMQ2WeTGT0DLJexZRoG6a1gO2afczmj42dKdfgJ4c7ik9aKAu2GsZ0PuwB2FW8p/S+Crl/rIyKiB90aDhgxf4yf7Ie1vJWLKdeGWVxgIbrWLAEuL7CLf8+n9K20TjgLqm+475fhR3JK3+1zdBhGlL5pPWNwIssFeaVOZc8cnNqRzZ2UO2RUGGofMWU7XAscmfDBCYcqqGFlsxbdZ0=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    tags: true
    repo: xebialabs-community/xld-logreport-plugin
